feat: adding cache functionality
defi-wonderland/sidechain-oracles pull request #5
Opened 2024-08-19 16:00 UTC by wei3erHase

2024-08-20 19:16 UTC, 0xJabberwock approved these changes
Comments are 🔥!

2024-08-20 19:16 UTC, 0xJabberwock commented on test/e2e/data-receiver.spec.ts
> +        await dataReceiver.addObservations([[0, 0]] as unknown as IOracleSidechain.ObservationDataStruct[], salt, nonce - 1);
Is casting to `unknown` first required?

2024-08-20 19:16 UTC, 0xJabberwock commented on test/unit/DataFeed.spec.ts
> -            expect(eventObservationsData).to.eql(observationsData);
Has the deleted expectation stopped working?

2024-08-20 20:14 UTC, wei3erHase commented on test/e2e/data-receiver.spec.ts
> +        await dataReceiver.addObservations([[0, 0]] as unknown as IOracleSidechain.ObservationDataStruct[], salt, nonce - 1);
yup :cries in ts:

2024-08-20 20:14 UTC, wei3erHase commented on test/unit/DataFeed.spec.ts
> -            expect(eventObservationsData).to.eql(observationsData);
stopped existing!

2024-08-20 20:53 UTC, 0xJabberwock commented on test/unit/DataFeed.spec.ts
> -            expect(eventObservationsData).to.eql(observationsData);
What do you mean? `PoolObserved` event still emits `_observationsData`.

2024-08-20 21:48 UTC, 0xJabberwock requested changes

2024-08-20 21:48 UTC, 0xJabberwock commented on solidity/contracts/DataReceiver.sol
> +        _cachedObservations[_poolSalt][_poolNonce].push(_observationsData[_i]);
Beware! The behavior of `_cachedObservations[_poolSalt][_poolNonce] = _observationsData` is not equal to `_cachedObservations[_poolSalt][_poolNonce].push(_observationsData[_i])`. The assignment would override the storage array but `push()` adds to it.

2024-08-21 10:21 UTC, wei3erHase commented on test/unit/DataFeed.spec.ts
> -            expect(eventObservationsData).to.eql(observationsData);
oh!!

2024-08-21 10:24 UTC, wei3erHase commented on solidity/contracts/DataReceiver.sol
> +        _cachedObservations[_poolSalt][_poolNonce].push(_observationsData[_i]);
great catch!

2024-08-21 16:39 UTC, 0xJabberwock approved these changes
👍

2024-08-21 16:39 UTC, 0xJabberwock commented on test/e2e/data-receiver.spec.ts
> +          tx = await dataReceiver.syncObservations(salt, 0);
`'should add the observations...'`

2024-08-21 16:40 UTC, 0xJabberwock commented on solidity/interfaces/IDataReceiver.sol
> +  /// @notice Allows any address to attemt to insert cached observations
`Allows any address to attempt to...`

2024-08-21 17:16 UTC, merged